strictness: veryhigh
autodetect: yes
doc-warnings: yes
max-line-length: 120
ignore-paths:
    - config
    - lecturer_database/
    - tests/
    - setup.py
    - tests_init
    - sub_tester.py
    - pub_tester.py

ignore-patterns:
    - .*\.doc
    - .*\.docx
    - .*\.odt
    - .*\.pdf
    - .*README.*


