strictness: veryhigh
autodetect: yes
doc-warnings: yes
max-line-length: 120
# ignore-paths:
#     - config
#     - lecturer_database
#     - tests_int

# ignore-patterns:
#     - .*\.doc
#     - .*\.docx
#     - .*\.odt
#     - .*\.pdf
#     - .*README.*
#

