strictness: veryhigh
autodetect: yes
doc-warnings: yes
max-line-length: 120
ignore-paths:
    - docs
    - config
    - lecturer_database
    - build
    - dist
    - tests/
    - setup.py


ignore-patterns:
    - .*\.doc
    - .*\.docx
    - .*\.odt
    - .*\.pdf
