output-format: grouped

inherits:
    - strictness_veryhigh

ignore:
    - ^docs/
    - ^tests
    - config
    - lecturer_database
    - build
    - dist

pyroma:
  run: true

pylint:
  options:
    max-line-length: 120

pep8:
  options:
    max-line-length: 120
