language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  - sudo apt-get install  antiword odt2txt
  - sudo cp -r nltk_data /usr/share/nltk_data
  - pip install tox
  - pip install python-coveralls
script:
  - tox
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a64381de5ad5d8de7e24
    on_success: change
    on_failure: always
    on_start: false
